sudo: required
services:
  - docker

before_install:
  - docker build -t ghariharan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ghariharan/react-test npm test -- --coverage

after_success:
  - docker build -t ghariharan/multi-client ./client
  - docker build -t ghariharan/multi-ngnix ./nginx
  - docker build -t ghariharan/multi-server ./server
  - docker build -t ghariharan/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ghariharan/multi-client
  - docker push ghariharan/multi-ngnix
  - docker push ghariharan/multi-server
  - docker push ghariharan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-726046989903"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"